apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-php
  labels:
    app: sample-php
spec:
  selector:
    matchLabels:
      app: sample-php
  template:
    metadata:
      labels:
        app: sample-php
    spec:
      containers:
      - image: lightbulb/php7.4.33-apache
        name: php-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 80