apiVersion: v1
kind: Service
metadata:
  name: sample-php-svc
spec:
  ports:
  - name: "sample-php"
    targetPort: 80
    port: 80
  selector:
    app: sample-php
  type: LoadBalancer # Set the service type to LoadBalancer
