---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-php
  labels:
    app: sample-php
spec:
  selector:
    matchLabels:
      app: sample-php
  template:
    metadata:
      labels:
        app: sample-php
    spec:
      containers:
      - image: lightbulb233/php7.4.33-apache:v2
        name: php-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-php-svc
spec:
  ports:
  - name: "sample-php"
    targetPort: 80
    port: 80
  selector:
    app: sample-php
  type: LoadBalancer # Set the service type to LoadBalancer
